server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Headers Access-Control-Allow-Methods, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        # Auth Service Route
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth

        # Patient & Doctor Service Route
        - id: patient-doctor-service
          uri: lb://patient-doctor-service
          predicates:
            - Path=/api/v1/patients/**, /api/v1/doctors/**, /api/v1/prescriptions/**
          filters:
            - name: JwtAuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                key-resolver: "#{@userKeyResolver}"

        # Appointment Service Route
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointments/**, /ws-token/**
          filters:
            - name: JwtAuthenticationFilter

        # Billing & Inventory Service Route
        - id: billing-inventory-service
          uri: lb://billing-inventory-service
          predicates:
            - Path=/api/v1/billing/**, /api/v1/inventory/**, /api/v1/staff/**
          filters:
            - name: JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 9a6729264462c97444c1d6df1b35b6b8b0e8c8942b08343f11e9766bbd083457

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
